name: LeetCode Sync

on:
  schedule:
    - cron: "0 12 * * *"   # runs every day at 12:00 UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository with token
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3️⃣ Install dependencies
      - name: Install Requests
        run: pip install requests

      # 4️⃣ Run LeetCode sync script
      - name: Run Script
        run: python leetcode_sync.py

      # 5️⃣ Commit and push changes (only if any)
      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Daily LeetCode sync"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
